dataset_name: demo
embedding_columns:
- x
- y
- z
label_name: label
n_points: 20000
seed: 3
sidecar_columns:
- category
- boolean
- continuous
- feature
- target
target_dir: /datasets/demo
tile_size: 1000
tiles_dir: /datasets/demo/tiles
